name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        sed -i "s|moduleDescription = \"|moduleDescription = \"(${{ github.event.inputs.package_name }}) |g" module.gradle
        sed -i "s|com.game.packagename|${{ github.event.inputs.package_name }}|g" module/src/main/cpp/game.h
        ./gradlew :module:assembleRelease
    - name: Create Release and Upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.package_name }}-${{ github.run_number }}
        name: Release ${{ github.event.inputs.package_name }}
        files: |
          out/magisk_module_release/*.zip
          out/magisk_module_release/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}